data:extend ({
{ type = "recipe", name = "compressed-iron", category = "compression", enabled = "false", ingredients = {{"iron-plate", 100},}, result = "compressed-iron", result_count = 1,},
{ type = "recipe", name = "compressed-copper", category = "compression", enabled = "false", ingredients = {{"copper-plate", 100}}, result = "compressed-copper", result_count = 1 },
{ type = "recipe", name = "uncompressed-iron", category = "decompression", enabled = "false", ingredients = {{"compressed-iron", 1}}, result = "iron-plate", subgroup = "uncompression", result_count = 100 },
{ type = "recipe", name = "uncompressed-copper", category = "decompression", enabled = "false", ingredients = {{"compressed-copper", 1}}, result = "copper-plate", subgroup = "uncompression", result_count = 100 },
{ type = "recipe", name = "compressed-stone", category = "compression", enabled = "false", ingredients= {{"stone",50}}, result = "compressed-stone", result_count = 1  },
{ type = "recipe", name = "compressed-coal", category = "compression", enabled = "false", ingredients= {{"coal",50}}, result = "compressed-coal", result_count = 1 },
{ type = "recipe", name = "compressed-logs", category = "compression", enabled = "false", ingredients= {{"raw-wood",50}}, result = "compressed-logs", result_count = 1 },
{ type = "recipe", name = "uncompressed-stone", category = "decompression", enabled = "false", ingredients= {{"compressed-stone",1}}, result = "stone", subgroup = "uncompression", result_count = 50 },
{ type = "recipe", name = "uncompressed-logs", category = "decompression", enabled = "false", ingredients= {{"compressed-logs",1}}, result = "raw-wood", subgroup = "uncompression", result_count = 50 },
{ type = "recipe", name = "uncompressed-coal", category = "decompression", enabled = "false", ingredients= {{"compressed-coal",1}}, result = "coal", subgroup = "uncompression", result_count = 50 },
{ type = "recipe", name = "compressor", category = "crafting", enabled = "false", ingredients = {{"iron-plate",10},{"copper-plate",20},{"electronic-circuit",30},}, result = "compressor", },
{ type = "recipe", name = "uncompressor",category = "crafting", enabled = "false", ingredients = {{"iron-plate",10},{"copper-plate",20},{"electronic-circuit",30},}, result = "uncompressor", },
{ type = "recipe", name = "compressed-steel", category = "compression", enabled = "false", ingredients = {{"steel-plate",100}}, result = "compressed-steel", },
{ type = "recipe", name = "uncompressed-steel", category = "decompression", enabled = "false", ingredients = {{"compressed-steel",1}}, result = "steel-plate", subgroup = "uncompression", result_count = 100, },
{ type = "recipe", name = "compressed-circuit1", category = "compression", enabled = "false", ingredients = {{"electronic-circuit",200}}, result = "compressed-circuit1", },
{ type = "recipe", name = "uncompressed-circuit1", category = "decompression", enabled = "false", ingredients = {{"compressed-circuit1",1}}, result = "electronic-circuit", subgroup = "uncompression", result_count = 200, },

{ type = "recipe", name = "compressed-processing-unit", category = "compression", enabled = "false", ingredients = {{"processing-unit",100}}, result = "compressed-processing-unit", },
{ type = "recipe", name = "uncompressed-processing-unit", category = "decompression", enabled = "false", ingredients ={{"compressed-processing-unit",1}}, result = "processing-unit", subgroup = "uncompression", result_count = 100, },
{ type = "recipe", name = "compressed-belt1", category = "compression", enabled = "false", ingredients = {{"transport-belt",50}}, result = "compressed-belt1", },
{ type = "recipe", name = "uncompressed-belt1", category = "decompression", enabled = "false", ingredients = {{"compressed-belt1",1}}, result = "transport-belt", subgroup = "uncompression", result_count = 50, },
{ type = "recipe", name = "compressed-circuit2", category = "compression", enabled = "false", ingredients = {{"advanced-circuit",200}}, result = "compressed-circuit2", },
{ type = "recipe", name = "uncompressed-circuit2", category = "decompression", enabled = "false", ingredients = {{"compressed-circuit2",1}}, result = "advanced-circuit", subgroup = "uncompression", result_count = 200, },
{ type = "recipe", name = "compressed-bullet1", category = "compression", enabled = "false", ingredients = {{"firearm-magazine",100}}, result = "compressed-bullet1", },
{ type = "recipe", name = "uncompressed-bullet1", category = "decompression", enabled = "false", ingredients = {{"compressed-bullet1",1}}, result = "firearm-magazine", subgroup = "uncompression", result_count = 100, },
{ type = "recipe", name = "compressed-grenade", category = "compression", enabled = "false", ingredients = {{"grenade",100}}, result = "compressed-grenade", },
{ type = "recipe", name = "uncompressed-grenade", category = "decompression", enabled = "false", ingredients = {{"compressed-grenade",1}}, result = "grenade", subgroup = "uncompression", result_count = 100, },
{ type = "recipe", name = "compressed-inserter", category = "compression", enabled = "false", ingredients = {{"inserter",50}}, result = "compressed-inserter", },
{ type = "recipe", name = "uncompressed-inserter", category = "decompression", enabled = "false", ingredients = {{"compressed-inserter",1}}, result = "inserter", subgroup = "uncompression", result_count = 50, },
{ type = "recipe", name = "compressed-splitter", category = "compression", enabled = "false", ingredients = {{"splitter",50}}, result = "compressed-splitter", },
{ type = "recipe", name = "uncompressed-splitter", category = "decompression", enabled = "false", ingredients = {{"compressed-splitter",1}}, result = "splitter", subgroup = "uncompression", result_count = 50, },
{ type = "recipe", name = "compressed-underground", category = "compression", enabled = "false", ingredients = {{"underground-belt",50}}, result = "compressed-underground", },
{ type = "recipe", name = "uncompressed-underground", category = "decompression", enabled = "false", ingredients = {{"compressed-underground",1}}, result = "underground-belt", subgroup = "uncompression", result_count = 50, },
{ type = "recipe", name = "compressed-battery", category = "compression", enabled = "false", ingredients = {{"battery",50}}, result = "compressed-battery", },
{ type = "recipe", name = "uncompressed-battery", category = "decompression", enabled = "false", ingredients = {{"compressed-battery",1}}, result = "battery", subgroup = "uncompression", result_count = 50, },
{ type = "recipe", name = "compressed-cannon-shell", category = "compression", enabled = "false", ingredients = {{"cannon-shell",50}}, result = "compressed-cannon-shell", },
{ type = "recipe", name = "uncompressed-cannon-shell", category = "decompression", enabled = "false", ingredients = {{"compressed-cannon-shell",1}}, result = "cannon-shell", subgroup = "uncompression", result_count = 50, },
{ type = "recipe", name = "compressed-concrete", category = "compression", enabled = "false", ingredients = {{"concrete",50}}, result = "compressed-concrete", },
{ type = "recipe", name = "uncompressed-concrete", category = "decompression", enabled = "false", ingredients = {{"compressed-concrete",1}}, result = "concrete", subgroup = "uncompression", result_count = 50, },
{ type = "recipe", name = "compressed-copper-ore", category = "compression", enabled = "false", ingredients = {{"copper-ore",50}}, result = "compressed-copper-ore", },
{ type = "recipe", name = "uncompressed-copper-ore", category = "decompression", enabled = "false", ingredients = {{"compressed-copper-ore",1}}, result = "copper-ore", subgroup = "uncompression", result_count = 50, },
{ type = "recipe", name = "compressed-iron-ore", category = "compression", enabled = "false", ingredients = {{"iron-ore",50}}, result = "compressed-iron-ore", },
{ type = "recipe", name = "uncompressed-iron-ore", category = "decompression", enabled = "false", ingredients = {{"compressed-iron-ore",1}}, result = "iron-ore", subgroup = "uncompression", result_count = 50,},
--{ type = "recipe", name = "compressed-rail2", category = "decompression", enabled = "false", ingredients = {{"curved-rail",50}}, result = "compressed-rail2", },
--{ type = "recipe", name = "uncompressed-rail2", category = "decompression", enabled = "false", ingredients = {{"compressed-rail2",1}}, result = "curved-rail", subgroup = "uncompression", result_count = 50, },
{ type = "recipe", name = "compressed-rail", category = "compression", enabled = "false", ingredients = {{"rail",100}}, result = "compressed-rail", },
{ type = "recipe", name = "uncompressed-rail", category = "decompression", enabled = "false", ingredients = {{"compressed-rail",1}}, result = "rail", subgroup = "uncompression", result_count = 100, },




{
type = "recipe",
name = "compressed-fast-inserter",
category = "compression", enabled = "false",
ingredients = {{"fast-inserter",50},},
result = "compressed-fast-inserter"
},
{
type = "recipe",
name = "uncompressed-fast-inserter",
category = "decompression", enabled = "false",
ingredients = {{"compressed-fast-inserter",1},},
result = "fast-inserter",
subgroup = "uncompression",
result_count = 50
},

{type = "recipe",
name = "compressed-solid-fuel",
category = "compression", enabled = "false",
ingredients = {{"solid-fuel",50},},
result = "compressed-solid-fuel"
},
{type = "recipe",
name = "uncompressed-solid-fuel",
category = "decompression", enabled = "false",
ingredients = {{"compressed-solid-fuel",1},},
result = "solid-fuel",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-fast-transport-belt",
category = "compression", enabled = "false",
ingredients = {{"fast-transport-belt",50},},
result = "compressed-fast-transport-belt",
},
{type = "recipe",
name = "uncompressed-fast-transport-belt",
category = "decompression", enabled = "false",
ingredients = {{"compressed-fast-transport-belt",1},},
result = "fast-transport-belt",
subgroup = "uncompression",
result_count = 50
},

{type = "recipe",
name = "compressed-piercing-bullet-magazine",
category = "compression", enabled = "false",
ingredients = {{"piercing-rounds-magazine",100},},
result = "compressed-piercing-bullet-magazine",
},
{type = "recipe",
name = "uncompressed-piercing-bullet-magazine",
category = "decompression", enabled = "false",
ingredients = {{"compressed-piercing-bullet-magazine",1},},
result = "piercing-rounds-magazine",
subgroup = "uncompression",
result_count = 100
},

{type = "recipe",
name = "compressed-piercing-shotgun-shell",
category = "compression", enabled = "false",
ingredients = {{"piercing-shotgun-shell",100},},
result = "compressed-piercing-shotgun-shell",
},
{type = "recipe",
name = "uncompressed-piercing-shotgun-shell",
category = "decompression", enabled = "false",
ingredients = {{"compressed-piercing-shotgun-shell",1},},
result = "piercing-shotgun-shell",
subgroup = "uncompression",
result_count = 100
},
{type = "recipe",
name = "compressed-fast-splitter",
category = "compression", enabled = "false",
ingredients = {{"fast-splitter",50},},
result = "compressed-fast-splitter",
},
{type = "recipe",
name = "uncompressed-fast-splitter",
category = "decompression", enabled = "false",
ingredients = {{"compressed-fast-splitter",1},},
result = "fast-splitter",
subgroup = "uncompression",
result_count = 50
},

{type = "recipe",
name = "compressed-fast-transport-belt-to-ground",
category = "compression", enabled = "false",
ingredients = {{"fast-underground-belt",50},},
result = "compressed-fast-transport-belt-to-ground",
},
{type = "recipe",
name = "uncompressed-fast-transport-belt-to-ground",
category = "decompression", enabled = "false",
ingredients = {{"compressed-fast-transport-belt-to-ground",1},},
result = "fast-underground-belt",
subgroup = "uncompression",
result_count = 50
},

{type = "recipe",
name = "compressed-express-transport-belt",
category = "compression", enabled = "false",
ingredients = {{"express-transport-belt",50},},
result = "compressed-express-transport-belt",
},
{type = "recipe",
name = "uncompressed-express-transport-belt",
category = "decompression", enabled = "false",
ingredients = {{"compressed-express-transport-belt",1},},
result = "express-transport-belt",
subgroup = "uncompression",
result_count = 50
},

{type = "recipe",
name = "compressed-express-transport-belt-to-ground",
category = "compression", enabled = "false",
ingredients = {{"express-underground-belt",50},},
result = "compressed-express-transport-belt-to-ground",
},
{type = "recipe",
name = "uncompressed-express-transport-belt-to-ground",
category = "decompression", enabled = "false",
ingredients = {{"compressed-express-transport-belt-to-ground",1},},
result = "express-underground-belt",
subgroup = "uncompression",
result_count = 50
},

{type = "recipe",
name = "compressed-express-splitter",
category = "compression", enabled = "false",
ingredients = {{"express-splitter",50},},
result = "compressed-express-splitter",
},
{type = "recipe",
name = "uncompressed-express-splitter",
category = "decompression", enabled = "false",
ingredients = {{"compressed-express-splitter",1},},
result = "express-splitter",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-roboport",
category = "compression", enabled = "false",
ingredients = {{"roboport",5},},
result = "compressed-roboport",
},
{type = "recipe",
name = "uncompressed-roboport",
category = "decompression", enabled = "false",
ingredients = {{"compressed-roboport",1},},
result = "roboport",
subgroup = "uncompression",
result_count = 5
},
{type = "recipe",
name = "compressed-stone-brick",
category = "compression", enabled = "false",
ingredients = {{"stone-brick",100},},
result = "compressed-stone-brick",
},
{type = "recipe",
name = "uncompressed-stone-brick",
category = "decompression", enabled = "false",
ingredients = {{"compressed-stone-brick",1},},
result = "stone-brick",
subgroup = "uncompression",
result_count = 100
},
{type = "recipe",
name = "compressed-tank",
category = "compression", enabled = "false",
ingredients = {{"tank",10},},
result = "compressed-tank",
},
{type = "recipe",
name = "uncompressed-tank",
category = "decompression", enabled = "false",
ingredients = {{"compressed-tank",1},},
result = "tank",
subgroup = "uncompression",
result_count =10 
},

{type = "recipe",
name = "compressed-long-handed-inserter",
category = "compression", enabled = "false",
ingredients = {{"long-handed-inserter",50},},
result = "compressed-long-handed-inserter",
},
{type = "recipe",
name = "uncompressed-long-handed-inserter",
category = "decompression", enabled = "false",
ingredients = {{"compressed-long-handed-inserter",1},},
result = "long-handed-inserter",
subgroup = "uncompression",
result_count = 50
},

{type = "recipe",
name = "compressed-pipe",
category = "compression", enabled = "false",
ingredients = {{"pipe",50},},
result = "compressed-pipe",
},
{type = "recipe",
name = "uncompressed-pipe",
category = "decompression", enabled = "false",
ingredients = {{"compressed-pipe",1},},
result = "pipe",
subgroup = "uncompression",
result_count = 50 
},
{type = "recipe",
name = "compressed-pipe-to-ground",
category = "compression", enabled = "false",
ingredients = {{"pipe-to-ground",50},},
result = "compressed-pipe-to-ground",
},
{type = "recipe",
name = "uncompressed-pipe-to-ground",
category = "decompression", enabled = "false",
ingredients = {{"compressed-pipe-to-ground",1},},
result = "pipe-to-ground",
subgroup = "uncompression",
result_count = 50
},

{type = "recipe",
name = "compressed-smart-inserter",
category = "compression", enabled = "false",
ingredients = {{"filter-inserter",50},},
result = "compressed-smart-inserter",
},
{type = "recipe",
name = "uncompressed-smart-inserter",
category = "decompression", enabled = "false",
ingredients = {{"compressed-smart-inserter",1},},
result = "filter-inserter",
subgroup = "uncompression",
result_count = 50
},

{type = "recipe",
name = "compressed-logistic-robot",
category = "compression", enabled = "false",
ingredients = {{"logistic-robot",50},},
result = "compressed-logistic-robot",
},
{type = "recipe",
name = "uncompressed-logistic-robot",
category = "decompression", enabled = "false",
ingredients = {{"compressed-logistic-robot",1},},
result = "logistic-robot",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-construction-robot",
category = "compression", enabled = "false",
ingredients = {{"construction-robot",50},},
result = "compressed-construction-robot",
},
{type = "recipe",
name = "uncompressed-construction-robot",
category = "decompression", enabled = "false",
ingredients = {{"compressed-construction-robot",1},},
result = "construction-robot",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-flying-robot-frame",
category = "compression", enabled = "false",
ingredients = {{"flying-robot-frame",50},},
result = "compressed-flying-robot-frame",
},
{type = "recipe",
name = "uncompressed-flying-robot-frame",
category = "decompression", enabled = "false",
ingredients = {{"compressed-flying-robot-frame",1},},
result = "flying-robot-frame",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-rail-chain-signal",
category = "compression", enabled = "false",
ingredients = {{"rail-chain-signal",50},},
result = "compressed-rail-chain-signal",
},
{type = "recipe",
name = "uncompressed-rail-chain-signal",
category = "decompression", enabled = "false",
ingredients = {{"compressed-rail-chain-signal",1},},
result = "rail-chain-signal",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-rail-signal",
category = "compression", enabled = "false",
ingredients = {{"rail-signal",50},},
result = "compressed-rail-signal",
},
{type = "recipe",
name = "uncompressed-rail-signal",
category = "decompression", enabled = "false",
ingredients = {{"compressed-rail-signal",1},},
result = "rail-signal",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-small-electric-pole",
category = "compression", enabled = "false",
ingredients = {{"small-electric-pole",50},},
result = "compressed-small-electric-pole",
},
{type = "recipe",
name = "uncompressed-small-electric-pole",
category = "decompression", enabled = "false",
ingredients = {{"compressed-small-electric-pole",1},},
result = "small-electric-pole",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-medium-electric-pole",
category = "compression", enabled = "false",
ingredients = {{"medium-electric-pole",50},},
result = "compressed-medium-electric-pole",
},
{type = "recipe",
name = "uncompressed-medium-electric-pole",
category = "decompression", enabled = "false",
ingredients = {{"compressed-medium-electric-pole",1},},
result = "medium-electric-pole",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-substation",
category = "compression", enabled = "false",
ingredients = {{"substation",50},},
result = "compressed-substation",
},
{type = "recipe",
name = "uncompressed-substation",
category = "decompression", enabled = "false",
ingredients = {{"compressed-substation",1},},
result = "substation",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-explosive-cannon-shell",
category = "compression", enabled = "false",
ingredients = {{"explosive-cannon-shell",50},},
result = "compressed-explosive-cannon-shell",
},
{type = "recipe",
name = "uncompressed-explosive-cannon-shell",
category = "decompression", enabled = "false",
ingredients = {{"compressed-explosive-cannon-shell",1},},
result = "explosive-cannon-shell",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-rocket",
category = "compression", enabled = "false",
ingredients = {{"rocket",50},},
result = "compressed-rocket",
},
{type = "recipe",
name = "uncompressed-rocket",
category = "decompression", enabled = "false",
ingredients = {{"compressed-rocket",1},},
result = "rocket",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-explosive-rocket",
category = "compression", enabled = "false",
ingredients = {{"explosive-rocket",50},},
result = "compressed-explosive-rocket",
},
{type = "recipe",
name = "uncompressed-explosive-rocket",
category = "decompression", enabled = "false",
ingredients = {{"compressed-explosive-rocket",1},},
result = "explosive-rocket",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-engine-unit",
category = "compression", enabled = "false",
ingredients = {{"engine-unit",50},},
result = "compressed-engine-unit",
},
{type = "recipe",
name = "uncompressed-engine-unit",
category = "decompression", enabled = "false",
ingredients = {{"compressed-engine-unit",1},},
result = "engine-unit",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-electric-engine-unit",
category = "compression", enabled = "false",
ingredients = {{"electric-engine-unit",50},},
result = "compressed-electric-engine-unit",
},
{type = "recipe",
name = "uncompressed-electric-engine-unit",
category = "decompression", enabled = "false",
ingredients = {{"compressed-electric-engine-unit",1},},
result = "electric-engine-unit",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-steel-axe",
category = "compression", enabled = "false",
ingredients = {{"steel-axe",20},},
result = "compressed-steel-axe",
},
{type = "recipe",
name = "uncompressed-steel-axe",
category = "decompression", enabled = "false",
ingredients = {{"compressed-steel-axe",1},},
result = "steel-axe",
subgroup = "uncompression",
result_count = 20
},
{type = "recipe",
name = "compressed-solar-panel",
category = "compression", enabled = "false",
ingredients = {{"solar-panel",50},},
result = "compressed-solar-panel",
},
{type = "recipe",
name = "uncompressed-solar-panel",
category = "decompression", enabled = "false",
ingredients = {{"compressed-solar-panel",1},},
result = "solar-panel",
subgroup = "uncompression",
result_count = 50
},

{type = "recipe",
name = "compressed-basic-accumulator",
category = "compression", enabled = "false",
ingredients = {{"accumulator",50},},
result = "compressed-basic-accumulator",
},
{type = "recipe",
name = "uncompressed-basic-accumulator",
category = "decompression", enabled = "false",
ingredients = {{"compressed-basic-accumulator",1},},
result = "accumulator",
subgroup = "uncompression",
result_count = 50
},

{type = "recipe",
name = "compressed-plastic-bar",
category = "compression", enabled = "false",
ingredients = {{"plastic-bar",100},},
result = "compressed-plastic-bar",
},
{type = "recipe",
name = "uncompressed-plastic-bar",
category = "decompression", enabled = "false",
ingredients = {{"compressed-plastic-bar",1},},
result = "plastic-bar",
subgroup = "uncompression",
result_count = 100
},
{type = "recipe",
name = "compressed-copper-cable",
category = "compression", enabled = "false",
energy_required = 4,
ingredients = {{"copper-cable",200},},
result = "compressed-copper-cable",
},
{type = "recipe",
name = "uncompressed-copper-cable",
category = "decompression", enabled = "false",
energy_required = 4,
ingredients = {{"compressed-copper-cable",1},},
result = "copper-cable",
subgroup = "uncompression",
result_count = 200
},
{type = "recipe",
name = "compressed-explosives",
category = "compression", enabled = "false",
ingredients = {{"explosives",50},},
result = "compressed-explosives",
},
{type = "recipe",
name = "uncompressed-explosives",
category = "decompression", enabled = "false",
ingredients = {{"compressed-explosives",1},},
result = "explosives",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-sulfur",
category = "compression", enabled = "false",
ingredients = {{"sulfur",50},},
result = "compressed-sulfur",
},
{type = "recipe",
name = "uncompressed-sulfur",
category = "decompression", enabled = "false",
ingredients = {{"compressed-sulfur",1},},
result = "sulfur",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-flame-thrower-ammo",
category = "compression", enabled = "false",
ingredients = {{"flame-thrower-ammo",50},},
result = "compressed-flame-thrower-ammo",
},
{type = "recipe",
name = "uncompressed-flame-thrower-ammo",
category = "decompression", enabled = "false",
ingredients = {{"compressed-flame-thrower-ammo",1},},
result = "flame-thrower-ammo",
subgroup = "uncompression",
result_count = 50
},

{type = "recipe",
name = "compressed-basic-mining-drill",
category = "compression", enabled = "false",
ingredients = {{"electric-mining-drill",50},},
result = "compressed-basic-mining-drill",
},
{type = "recipe",
name = "uncompressed-basic-mining-drill",
category = "decompression", enabled = "false",
ingredients = {{"compressed-basic-mining-drill",1},},
result = "electric-mining-drill",
subgroup = "uncompression",
result_count = 50
},

{type = "recipe",
name = "compressed-train-stop",
category = "compression", enabled = "false",
ingredients = {{"train-stop",10},},
result = "compressed-train-stop",
},
{type = "recipe",
name = "uncompressed-train-stop",
category = "decompression", enabled = "false",
ingredients = {{"compressed-train-stop",1},},
result = "train-stop",
subgroup = "uncompression",
result_count = 10
},
{type = "recipe",
name = "compressed-big-electric-pole",
category = "compression", enabled = "false",
ingredients = {{"big-electric-pole",50},},
result = "compressed-big-electric-pole",
},
{type = "recipe",
name = "uncompressed-big-electric-pole",
category = "decompression", enabled = "false",
ingredients = {{"compressed-big-electric-pole",1},},
result = "big-electric-pole",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-laser-turret",
category = "compression", enabled = "false",
ingredients = {{"laser-turret",50},},
result = "compressed-laser-turret",
},
{type = "recipe",
name = "uncompressed-laser-turret",
category = "decompression", enabled = "false",
ingredients = {{"compressed-laser-turret",1},},
result = "laser-turret",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-storage-tank",
category = "compression", enabled = "false",
ingredients = {{"storage-tank",15},},
result = "compressed-storage-tank",
},
{type = "recipe",
name = "uncompressed-storage-tank",
category = "decompression", enabled = "false",
ingredients = {{"compressed-storage-tank",1},},
result = "storage-tank",
subgroup = "uncompression",
result_count = 15
},
{type = "recipe",
name = "compressed-steam-engine",
category = "compression", enabled = "false",
ingredients = {{"steam-engine",10},},
result = "compressed-steam-engine",
},
{type = "recipe",
name = "uncompressed-steam-engine",
category = "decompression", enabled = "false",
ingredients = {{"compressed-steam-engine",1},},
result = "steam-engine",
subgroup = "uncompression",
result_count = 10
},
{type = "recipe",
name = "compressed-shotgun-shell",
category = "compression", enabled = "false",
ingredients = {{"shotgun-shell",100},},
result = "compressed-shotgun-shell",
},
{type = "recipe",
name = "uncompressed-shotgun-shell",
category = "decompression", enabled = "false",
ingredients = {{"compressed-shotgun-shell",1},},
result = "shotgun-shell",
subgroup = "uncompression",
result_count = 100
},
{type = "recipe",
name = "compressed-steel-furnace",
category = "compression", enabled = "false",
ingredients = {{"steel-furnace",10},},
result = "compressed-steel-furnace",
},
{type = "recipe",
name = "uncompressed-steel-furnace",
category = "decompression", enabled = "false",
ingredients = {{"compressed-steel-furnace",1},},
result = "steel-furnace",
subgroup = "uncompression",
result_count = 10
},
{type = "recipe",
name = "compressed-stone-furnace",
category = "compression", enabled = "false",
ingredients = {{"stone-furnace",10},},
result = "compressed-stone-furnace",
},
{type = "recipe",
name = "uncompressed-stone-furnace",
category = "decompression", enabled = "false",
ingredients = {{"compressed-stone-furnace",1},},
result = "stone-furnace",
subgroup = "uncompression",
result_count = 10
},
{type = "recipe",
name = "compressed-chemical-plant",
category = "compression", enabled = "false",
ingredients = {{"chemical-plant",10},},
result = "compressed-chemical-plant",
},
{type = "recipe",
name = "uncompressed-chemical-plant",
category = "decompression", enabled = "false",
ingredients = {{"compressed-chemical-plant",1},},
result = "chemical-plant",
subgroup = "uncompression",
result_count = 10
},
{type = "recipe",
name = "compressed-repair-pack",
category = "compression", enabled = "false",
ingredients = {{"repair-pack",50},},
result = "compressed-repair-pack",
},
{type = "recipe",
name = "uncompressed-repair-pack",
category = "decompression", enabled = "false",
ingredients = {{"compressed-repair-pack",1},},
result = "repair-pack",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-electric-furnace",
category = "compression", enabled = "false",
ingredients = {{"electric-furnace",10},},
result = "compressed-electric-furnace",
},
{type = "recipe",
name = "uncompressed-electric-furnace",
category = "decompression", enabled = "false",
ingredients = {{"compressed-electric-furnace",1},},
result = "electric-furnace",
subgroup = "uncompression",
result_count = 10
},
{type = "recipe",
name = "compressed-land-mine",
category = "compression", enabled = "false",
ingredients = {{"land-mine",50},},
result = "compressed-land-mine",
},
{type = "recipe",
name = "uncompressed-land-mine",
category = "decompression", enabled = "false",
ingredients = {{"compressed-land-mine",1},},
result = "land-mine",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-speed-module",
category = "compression", enabled = "false",
ingredients = {{"speed-module",50},},
result = "compressed-speed-module",
},
{type = "recipe",
name = "uncompressed-speed-module",
category = "decompression", enabled = "false",
ingredients = {{"compressed-speed-module",1},},
result = "speed-module",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-speed-module-2",
category = "compression", enabled = "false",
ingredients = {{"speed-module-2",50},},
result = "compressed-speed-module-2",
},
{type = "recipe",
name = "uncompressed-speed-module-2",
category = "decompression", enabled = "false",
ingredients = {{"compressed-speed-module-2",1},},
result = "speed-module-2",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-speed-module-3",
category = "compression", enabled = "false",
ingredients = {{"speed-module-3",50},},
result = "compressed-speed-module-3",
},
{type = "recipe",
name = "uncompressed-speed-module-3",
category = "decompression", enabled = "false",
ingredients = {{"compressed-speed-module-3",1},},
result = "speed-module-3",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-logistic-chest-active-provider",
category = "compression", enabled = "false",
ingredients = {{"logistic-chest-active-provider",50},},
result = "compressed-logistic-chest-active-provider",
},
{type = "recipe",
name = "uncompressed-logistic-chest-active-provider",
category = "decompression", enabled = "false",
ingredients = {{"compressed-logistic-chest-active-provider",1},},
result = "logistic-chest-active-provider",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-logistic-chest-passive-provider",
category = "compression", enabled = "false",
ingredients = {{"logistic-chest-passive-provider",50},},
result = "compressed-logistic-chest-passive-provider",
},
{type = "recipe",
name = "uncompressed-logistic-chest-passive-provider",
category = "decompression", enabled = "false",
ingredients = {{"compressed-logistic-chest-passive-provider",1},},
result = "logistic-chest-passive-provider",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-logistic-chest-requester",
category = "compression", enabled = "false",
ingredients = {{"logistic-chest-requester",50},},
result = "compressed-logistic-chest-requester",
},
{type = "recipe",
name = "uncompressed-logistic-chest-requester",
category = "decompression", enabled = "false",
ingredients = {{"compressed-logistic-chest-requester",1},},
result = "logistic-chest-requester",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-logistic-chest-storage",
category = "compression", enabled = "false",
ingredients = {{"logistic-chest-storage",50},},
result = "compressed-logistic-chest-storage",
},
{type = "recipe",
name = "uncompressed-logistic-chest-storage",
category = "decompression", enabled = "false",
ingredients = {{"compressed-logistic-chest-storage",1},},
result = "logistic-chest-storage",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-defender-capsule",
category = "compression", enabled = "false",
ingredients = {{"defender-capsule",100},},
result = "compressed-defender-capsule",
},
{type = "recipe",
name = "uncompressed-defender-capsule",
category = "decompression", enabled = "false",
ingredients = {{"compressed-defender-capsule",1},},
result = "defender-capsule",
subgroup = "uncompression",
result_count = 100
},
{type = "recipe",
name = "compressed-destroyer-capsule",
category = "compression", enabled = "false",
ingredients = {{"destroyer-capsule",100},},
result = "compressed-destroyer-capsule",
},
{type = "recipe",
name = "uncompressed-destroyer-capsule",
category = "decompression", enabled = "false",
ingredients = {{"compressed-destroyer-capsule",1},},
result = "destroyer-capsule",
subgroup = "uncompression",
result_count = 100
},
{type = "recipe",
name = "compressed-distractor-capsule",
category = "compression", enabled = "false",
ingredients = {{"distractor-capsule",100},},
result = "compressed-distractor-capsule",
},
{type = "recipe",
name = "uncompressed-distractor-capsule",
category = "decompression", enabled = "false",
ingredients = {{"compressed-distractor-capsule",1},},
result = "distractor-capsule",
subgroup = "uncompression",
result_count = 100
},
{type = "recipe",
name = "compressed-poison-capsule",
category = "compression", enabled = "false",
ingredients = {{"poison-capsule",100},},
result = "compressed-poison-capsule",
},
{type = "recipe",
name = "uncompressed-poison-capsule",
category = "decompression", enabled = "false",
ingredients = {{"compressed-poison-capsule",1},},
result = "poison-capsule",
subgroup = "uncompression",
result_count = 100
},
{type = "recipe",
name = "compressed-slowdown-capsule",
category = "compression", enabled = "false",
ingredients = {{"slowdown-capsule",100},},
result = "compressed-slowdown-capsule",
},
{type = "recipe",
name = "uncompressed-slowdown-capsule",
category = "decompression", enabled = "false",
ingredients = {{"compressed-slowdown-capsule",1},},
result = "slowdown-capsule",
subgroup = "uncompression",
result_count = 100
},
{type = "recipe",
name = "compressed-pumpjack",
category = "compression", enabled = "false",
ingredients = {{"pumpjack",50},},
result = "compressed-pumpjack",
},
{type = "recipe",
name = "uncompressed-pumpjack",
category = "decompression", enabled = "false",
ingredients = {{"compressed-pumpjack",1},},
result = "pumpjack",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-science-pack-1",
category = "compression", enabled = "false",
ingredients = {{"science-pack-1",200},},
result = "compressed-science-pack-1",
},
{type = "recipe",
name = "uncompressed-science-pack-1",
category = "decompression", enabled = "false",
ingredients = {{"compressed-science-pack-1",1},},
result = "science-pack-1",
subgroup = "uncompression",
result_count = 200
},
{type = "recipe",
name = "compressed-science-pack-2",
category = "compression", enabled = "false",
ingredients = {{"science-pack-2",200},},
result = "compressed-science-pack-2",
},
{type = "recipe",
name = "uncompressed-science-pack-2",
category = "decompression", enabled = "false",
ingredients = {{"compressed-science-pack-2",1},},
result = "science-pack-2",
subgroup = "uncompression",
result_count = 200
},
{type = "recipe",
name = "compressed-science-pack-3",
category = "compression", enabled = "false",
ingredients = {{"science-pack-3",200},},
result = "compressed-science-pack-3",
},
{type = "recipe",
name = "uncompressed-science-pack-3",
category = "decompression", enabled = "false",
ingredients = {{"compressed-science-pack-3",1},},
result = "science-pack-3",
subgroup = "uncompression",
result_count = 200
},
{type = "recipe",
name = "compressed-effectivity-module",
category = "compression", enabled = "false",
ingredients = {{"effectivity-module",50},},
result = "compressed-effectivity-module",
},
{type = "recipe",
name = "uncompressed-effectivity-module",
category = "decompression", enabled = "false",
ingredients = {{"compressed-effectivity-module",1},},
result = "effectivity-module",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-effectivity-module-2",
category = "compression", enabled = "false",
ingredients = {{"effectivity-module-2",50},},
result = "compressed-effectivity-module-2",
},
{type = "recipe",
name = "uncompressed-effectivity-module-2",
category = "decompression", enabled = "false",
ingredients = {{"compressed-effectivity-module-2",1},},
result = "effectivity-module-2",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-effectivity-module-3",
category = "compression", enabled = "false",
ingredients = {{"effectivity-module-3",50},},
result = "compressed-effectivity-module-3",
},
{type = "recipe",
name = "uncompressed-effectivity-module-3",
category = "decompression", enabled = "false",
ingredients = {{"compressed-effectivity-module-3",1},},
result = "effectivity-module-3",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-productivity-module",
category = "compression", enabled = "false",
ingredients = {{"productivity-module",50},},
result = "compressed-productivity-module",
},
{type = "recipe",
name = "uncompressed-productivity-module",
category = "decompression", enabled = "false",
ingredients = {{"compressed-productivity-module",1},},
result = "productivity-module",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-productivity-module-2",
category = "compression", enabled = "false",
ingredients = {{"productivity-module-2",50},},
result = "compressed-productivity-module-2",
},
{type = "recipe",
name = "uncompressed-productivity-module-2",
category = "decompression", enabled = "false",
ingredients = {{"compressed-productivity-module-2",1},},
result = "productivity-module-2",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-productivity-module-3",
category = "compression", enabled = "false",
ingredients = {{"productivity-module-3",50},},
result = "compressed-productivity-module-3",
},
{type = "recipe",
name = "uncompressed-productivity-module-3",
category = "decompression", enabled = "false",
ingredients = {{"compressed-productivity-module-3",1},},
result = "productivity-module-3",
subgroup = "uncompression",
result_count = 50
},
{type = "recipe",
name = "compressed-satellite",
category = "compression", enabled = "false",
ingredients = {{"satellite",10},},
result = "compressed-satellite",
},
{type = "recipe",
name = "uncompressed-satellite",
category = "decompression", enabled = "false",
ingredients = {{"compressed-satellite",1},},
result = "satellite",
subgroup = "uncompression",
result_count = 10
},
{type = "recipe",
name = "compressed-rocket-fuel",
category = "compression", enabled = "false",
ingredients = {{"rocket-fuel",10},},
result = "compressed-rocket-fuel",
},
{type = "recipe",
name = "uncompressed-rocket-fuel",
category = "decompression", enabled = "false",
ingredients = {{"compressed-rocket-fuel",1},},
result = "rocket-fuel",
subgroup = "uncompression",
result_count = 10
},
{type = "recipe",
name = "compressed-rocket-control-unit",
category = "compression", enabled = "false",
ingredients = {{"rocket-control-unit",10},},
result = "compressed-rocket-control-unit",
},
{type = "recipe",
name = "uncompressed-rocket-control-unit",
category = "decompression", enabled = "false",
ingredients = {{"compressed-rocket-control-unit",1},},
result = "rocket-control-unit",
subgroup = "uncompression",
result_count = 10
},
category = "decompression",
energy_required = 4,
{type = "recipe",
name = "compressed-alien-artifact",
category = "compression", enabled = "false",
ingredients = {{"alien-artifact",500},},
result = "compressed-alien-artifact",
},
{type = "recipe",
name = "uncompressed-alien-artifact",
category = "decompression", enabled = "false",
ingredients = {{"compressed-alien-artifact",1},},
result = "alien-artifact",
subgroup = "uncompression",
result_count = 500
},
{type = "recipe",
name = "compressed-alien-science",
category = "compression", enabled = "false",
ingredients = {{"alien-science-pack",500},},
result = "compressed-alien-science",
},
{type = "recipe",
name = "uncompressed-alien-science",
category = "decompression", enabled = "false",
ingredients = {{"compressed-alien-science",1},},
result = "alien-science-pack",
subgroup = "uncompression",
result_count = 500
},

category = "compression",
energy_required = 4,
{type = "recipe",
name = "compressed-burner-inserter",
category = "compression", enabled = "false",
ingredients = {{"burner-inserter",50},},
result = "compressed-burner-inserter",
},
{type = "recipe",
name = "uncompressed-burner-inserter",
category = "decompression", enabled = "false",
ingredients = {{"compressed-burner-inserter",1},},
result = "burner-inserter",
subgroup = "uncompression",
result_count = 50
},
category = "compression",
energy_required = 4,
{type = "recipe",
name = "compressed-stack-inserter",
category = "compression", enabled = "false",
ingredients = {{"stack-inserter",50},},
result = "compressed-stack-inserter",
},
{type = "recipe",
name = "uncompressed-stack-inserter",
category = "decompression", enabled = "false",
ingredients = {{"compressed-stack-inserter",1},},
result = "stack-inserter",
subgroup = "uncompression",
result_count = 50
},
category = "compression",
energy_required = 4,
{type = "recipe",
name = "compressed-stack-filter-inserter",
category = "compression", enabled = "false",
ingredients = {{"stack-filter-inserter",50},},
result = "compressed-stack-filter-inserter",
},
{type = "recipe",
name = "uncompressed-stack-filter-inserter",
category = "decompression", enabled = "false",
ingredients = {{"compressed-stack-filter-inserter",1},},
result = "stack-filter-inserter",
subgroup = "uncompression",
result_count = 50
},
category = "compression",
energy_required = 4,
{type = "recipe",
name = "compressed-wood-chest",
category = "compression", enabled = "false",
ingredients = {{"wooden-chest",50},},
result = "compressed-wood-chest",
},
{type = "recipe",
name = "uncompressed-wood-chest",
category = "decompression", enabled = "false",
ingredients = {{"compressed-wood-chest",1},},
result = "wooden-chest",
subgroup = "uncompression",
result_count = 50
},
category = "compression",
energy_required = 4,
{type = "recipe",
name = "compressed-steel-chest",
category = "compression", enabled = "false",
ingredients = {{"steel-chest",50},},
result = "compressed-steel-chest",
},
{type = "recipe",
name = "uncompressed-steel-chest",
category = "decompression", enabled = "false",
ingredients = {{"compressed-steel-chest",1},},
result = "steel-chest",
subgroup = "uncompression",
result_count = 50
},
category = "compression",
energy_required = 4,
{type = "recipe",
name = "compressed-iron-chest",
category = "compression", enabled = "false",
ingredients = {{"iron-chest",50},},
result = "compressed-iron-chest",
},
{type = "recipe",
name = "uncompressed-iron-chest",
category = "decompression", enabled = "false",
ingredients = {{"compressed-iron-chest",1},},
result = "iron-chest",
subgroup = "uncompression",
result_count = 50
},


--[[
category = "compression",
energy_required = 4,
{type = "recipe",
name = "compressed-",
category = "compression", enabled = "true",
ingredients = {{"",50},},
result = "compressed-",
},
{type = "recipe",
name = "uncompressed-",
category = "decompression", enabled = "true",
ingredients = {{"compressed-",1},},
result = "",
subgroup = "uncompression",
result_count = 50
},


]]
})
